# Generated by Django 3.2.3 on 2021-05-29 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('createTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pos_api_app.category')),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('thumbUrl', models.CharField(max_length=15)),
                ('createTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField()),
            ],
        ),
    ]
